[package]
name = "pyo3-test"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.2", features = ["experimental-async", "extension-module"] }

[lib]
name="pyo3_test"
crate-type = ["cdylib", "rlib"]
